project:
  type: book
  output-dir: docs # default output directory is `_book`

book:
  title: "Quarto Book ไทย"
  author: "กิตติพศ ศิริวงศ์รังสรร"
  date: "6/13/2022"
  repo-url: https://github.com/Lightbridge-KS/quarto-book-thai-pdf
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    include-in-header: "thai-preamble.tex"
    keep-tex: true # (optional) `true` to keep intermediate LaTeX
    documentclass: scrreprt
  html:
    theme: cosmo




